Repository SS507-today/project-today-flutter, pull requests merged in 2024-08, with the labels that each got.

#2 프로젝트 세팅
  .github/ISSUE_TEMPLATE/bug-issue-template.md
  .github/ISSUE_TEMPLATE/epic-issue-template.md
  .github/ISSUE_TEMPLATE/feature-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  project_today/README.md
  project_today/assets/fonts/Pretendard-Black.ttf
  project_today/assets/fonts/Pretendard-Bold.ttf
  project_today/assets/fonts/Pretendard-ExtraBold.ttf
  project_today/assets/fonts/Pretendard-ExtraLight.ttf
  project_today/assets/fonts/Pretendard-Light.ttf
  project_today/assets/fonts/Pretendard-Medium.ttf
  project_today/assets/fonts/Pretendard-Regular.ttf
  project_today/assets/fonts/Pretendard-SemiBold.ttf
  project_today/assets/fonts/Pretendard-Thin.ttf
  project_today/lib/core/constant/colors.dart
  project_today/lib/core/constant/fonts.dart
  project_today/lib/core/constant/index.dart
  project_today/lib/core/utils/index.dart
  project_today/lib/data/models/index.dart
  project_today/lib/data/repositories/index.dart
  project_today/lib/data/services/index.dart
  project_today/lib/main.dart
  project_today/lib/screen/diary/diary_screens.dart
  project_today/lib/screen/diary/view/diary_view.dart
  project_today/lib/screen/diary/view_model/diary_view_model.dart
  project_today/lib/screen/group/group_screens.dart
  project_today/lib/screen/group/view/group_view.dart
  project_today/lib/screen/group/view_model/group_view_model.dart
  project_today/lib/screen/onboard/onboard_screens.dart
  project_today/lib/screen/onboard/view/onboard_view.dart
  project_today/lib/screen/onboard/view_model/onboard_view_model.dart
  project_today/lib/screen/screens_index.dart
  project_today/lib/screen/splash/splash_screens.dart
  project_today/lib/ui/atoms/index.dart
  project_today/lib/ui/molecules/index.dart
  project_today/lib/ui/organisms/index.dart
  project_today/lib/ui/templates/index.dart
  project_today/pubspec.yaml
Labels: EPIC

#5 스타일가이드 재세팅
  project_today/lib/core/constant/colors.dart
  project_today/lib/core/constant/fonts.dart
Labels: 🔨 Refactor, 🎨 styling

#9 깃허브 프로젝트 관리 세팅
  .github/labels.json
Labels: ⚙️ Setting, 📃 Docs

#12 공통 컴포넌트 개발
  project_today/assets/icon/toast_error.svg
  project_today/assets/icon/toast_success.svg
  project_today/assets/images/kakao.png
  project_today/lib/ui/atoms/customToast.dart
  project_today/lib/ui/atoms/defaultButton.dart
  project_today/lib/ui/atoms/defaultListEl.dart
  project_today/lib/ui/atoms/imgListEl.dart
  project_today/lib/ui/atoms/index.dart
  project_today/lib/ui/atoms/kakaoLoginButton.dart
  project_today/pubspec.yaml
Labels: ✨ Feature, 🙋‍♂️ Question, 🎨 styling
